service: go-sls-workshop

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMO_DB_TABLE:
      Ref: DynamoDBTable
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
     - "dynamodb:PutItem"
     - "dynamodb:GetItem"
     Resource:
       Fn::GetAtt:
       - DynamoDBTable
       - Arn

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: create
          method: post
          request:
            parameters:
              querystring:
                url: true
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: url-shortener
        KeySchema:
        - AttributeName: "url"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        AttributeDefinitions:
        - AttributeName: "url"
          AttributeType: "S"