service: go-sls-workshop

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
          request:
            parameters:
              querystring:
                name: true
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
